@extends('templates.glomaroffshore')
@section('content')
    @include('snippets.contentSections')
@endsection
@section('vessels')
    @include('snippets.vesselsSection')
@endsection
@section('news')
    @include('snippets.newsSection')
@endsection
